### ISSUE TITLE
2.0.1 crashes everywhere

### ISSUE THREAD

**Issue by mtl1979** [LetheanMovement/lethean#88] opened 2018-04-30 15:28 UTC
When running intense-blockchain-import, it throws error after saving block chain:
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
pure virtual method called
terminate called recursively

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```
It seems to import correctly as block height is updated but crashes on exit.
Pretty much need to constantly close daemon and run intense-blockchain-import or it will try to redownload everything from fork point to current height. Too many times I've tried to delete the database and import it from older backup. It doesn't work!

Using Windows 10 64-bit (version 1709 build 16299.371) on Intel Core 2 Duo E7300 @ 2.66 GHz, 4 GB ram, and binaries downloaded from GitHub.

**Comment by pallas1** [comment] 2018-04-30 15:32
Can't reproduce this on Linux, might be windows only or depending on boost version (I'm using 1.58)

**Comment by mtl1979** [comment] 2018-04-30 15:34
Does someone actually test the posted Windows binaries? Seems like every release so far has been broken since 1.4.2 ...

**Comment by valiant1x** [comment] 2018-05-02 05:17
>Pretty much need to constantly close daemon and run intense-blockchain-import or it will try to redownload everything from fork point to current height.

Can you clarify what you mean here? When are you using intense-blockchain-import and for what purpose?

**Comment by mtl1979** [comment] 2018-05-02 07:28
I use it to remove latest block, because otherwise it would keep redownloading it over and over... It doesn't happen very often, last time I synced from scratch, only 3 times...

**Comment by valiant1x** [comment] 2018-05-13 17:31
I can confirm a sporadic exit with the described error in 64 bit Windows. I had to run several tests before it was successful. However, since it is still properly popping blocks and the error upon exit seems more aesthetic than anything, I am not sure it's a high priority to fix.

**Comment by mtl1979** [comment] 2018-05-13 17:36
Some people got it also while syncing the daemon... I haven't seen it in a while, but I'm not surprised as it happens inside exception handler, which is usually bad situation in the first place.

**Comment by iedemam** [comment] 2018-10-15 17:32
Closing because we can't replicate this and I haven't seen a report in a long time.

Re-open and @ me if there's a trace to attach.

**Closed by iedemam** 2018-10-15 17:32 UTC
